[phases.setup]
nixPkgs = ["poetry"]

[phases.install]
cmds = [
    "python --version",
    "poetry export -f requirements.txt --output requirements.txt --without-hashes",
    "python -m pip install uvicorn[standard] -r requirements.txt --break-system-packages"
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
